### ISSUE TITLE
and where is this require ".bitbar/vendor/autoload.php"; ? 

### ISSUE THREAD

**Issue by ghost** [SteveEdson/bitbar-php#10]
Where did this vendor directory come from? 
Where is this autoload.php and what does it do? 
Why do you include a composer.json and tell us to add a new one with a different content? 

These are the worse instructions  Jesus https://github.com/SteveEdson/bitbar-php.

**Comment by ghost** [comment]
I wish this wasn't free so we could pay for proper instructions.

**Comment by SteveEdson** [comment]
I'd recommend reading https://scotch.io/tutorials/a-beginners-guide-to-composer to help you understand what composer is, and how to use it. But basically:

- Composer is a package manager for PHP (like node.js has `NPM`, Python has `pip`, Ruby has `gem` etc)
- You define the packages you want to use, in *your* project's `composer.json` file, for example, `steveedson/bitbar-php`
- When you run `composer install`, the packages are downloaded into your `/vendor` directory
- This directory also includes a `autoload.php` file, that you can `require` in order to start using the Bitbar classes provided in this repo

The `composer.json` file in *this* repo is used to specify what my dependencies are, and to tell packagist (the place where PHP composer projects are stored), how the project is set up, and named etc.

Hope this helps.

> I wish this wasn't free so we could pay for proper instructions.

Feel free to donate at https://www.paypal.me/steveedson

Thanks!
